const express=require("express"),cors=require("cors"),dotenv=require("dotenv"),Database=require("better-sqlite3"),crypto=require("crypto"),path=require("path"),fs=require("fs");
dotenv.config();
const app=express(),PORT=process.env.PORT||3000,BASE=process.env.PLUSPIX_BASE_URL||"https://api-pluspix.squareweb.app";
app.use(cors());app.use(express.json({limit:"12mb"}));app.use(express.static(__dirname));
const uploads=path.join(__dirname,"uploads");if(!fs.existsSync(uploads))fs.mkdirSync(uploads);
app.use("/uploads",express.static(uploads));
const db=new Database("plast_rodas.db");
db.exec(`CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,diameter TEXT NOT NULL DEFAULT '',finish TEXT NOT NULL DEFAULT '',price INTEGER NOT NULL,stock INTEGER NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT UNIQUE NOT NULL,customer_name TEXT,customer_email TEXT,customer_phone TEXT,customer_document TEXT,address TEXT,items_json TEXT,total INTEGER,status TEXT NOT NULL,transaction_id TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS payments(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id INTEGER,transaction_id TEXT UNIQUE,value INTEGER,status TEXT,raw_json TEXT,created_at TEXT NOT NULL);`);
const cols=db.prepare("PRAGMA table_info(products)").all().map(x=>x.name);
if(!cols.includes("description"))db.exec("ALTER TABLE products ADD COLUMN description TEXT NOT NULL DEFAULT ''");
if(!cols.includes("image"))db.exec("ALTER TABLE products ADD COLUMN image TEXT NOT NULL DEFAULT ''");
function headers(){return {"x-client-id":process.env.PLUSPIX_CLIENT_ID,"x-client-secret":process.env.PLUSPIX_CLIENT_SECRET,"Content-Type":"application/json"}}
function admin(req,res,next){const h=req.headers.authorization||"";if(h!=="Basic "+Buffer.from(`${process.env.ADMIN_USER||"admin"}:${process.env.ADMIN_PASSWORD||"change-me"}`).toString("base64"))return res.status(401).json({message:"Não autorizado"});next()}
function saveImage(data){if(!data||!String(data).startsWith("data:image/"))return "";const m=String(data).match(/^data:image\/(png|jpeg|jpg|webp);base64,(.+)$/);if(!m)return "";const ext=m[1]==="jpeg"?"jpg":m[1],name=`produto-${Date.now()}-${crypto.randomBytes(3).toString("hex")}.${ext}`;fs.writeFileSync(path.join(uploads,name),Buffer.from(m[2],"base64"));return "/uploads/"+name}
app.get("/api/products",(req,res)=>res.json(db.prepare("SELECT id,name,description,image,price,stock FROM products WHERE active=1 ORDER BY id DESC").all()));
app.get("/api/orders/:code",(req,res)=>{const o=db.prepare("SELECT code,customer_name,customer_email,total,status,transaction_id,created_at FROM orders WHERE code=?").get(req.params.code);if(!o)return res.status(404).json({message:"Pedido não encontrado"});res.json(o)});
app.post("/api/payment",async(req,res)=>{try{const {customer,items}=req.body;if(!customer||!items?.length)return res.status(400).json({message:"Dados do pedido incompletos"});let total=0,valid=[];for(const i of items){const p=db.prepare("SELECT * FROM products WHERE id=? AND active=1").get(i.id);if(!p||p.stock<i.qty)return res.status(400).json({message:`Produto indisponível: ${p?.name||i.id}`});total+=p.price*i.qty;valid.push({id:p.id,name:p.name,qty:i.qty,unitPrice:p.price})}const code="PR-"+Date.now().toString().slice(-8);const address=[customer.cep,customer.street,customer.number,customer.district,customer.city,customer.state].filter(Boolean).join(", ");const ins=db.prepare("INSERT INTO orders(code,customer_name,customer_email,customer_phone,customer_document,address,items_json,total,status,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)");const info=ins.run(code,customer.name,customer.email,customer.phone,customer.document,address,JSON.stringify(valid),total,"AGUARDANDO_PAGAMENTO",new Date().toISOString());const PIX_BASE="https://api.whitelabel-elite.com";const r=await fetch(PIX_BASE+"/v1/deposit",{method:"POST",headers:headers(),body:JSON.stringify({amount:total,description:`Venda #${code}`})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.transactionId){db.prepare("UPDATE orders SET status=? WHERE id=?").run("ERRO_PAGAMENTO",info.lastInsertRowid);return res.status(r.ok?502:r.status).json({message:d.message||"Falha ao criar PIX"})}db.prepare("UPDATE orders SET transaction_id=? WHERE id=?").run(d.transactionId,info.lastInsertRowid);db.prepare("INSERT INTO payments(order_id,transaction_id,value,status,raw_json,created_at) VALUES(?,?,?,?,?,?)").run(info.lastInsertRowid,d.transactionId,total,String(d.status||"PENDENTE"),JSON.stringify(d),new Date().toISOString());res.json({success:true,orderCode:code,transactionId:d.transactionId,qrcodeUrl:d.qrCode?.imageUrl||null,copyPaste:d.qrCode?.copyPaste||null,status:d.status})}catch(e){console.error(e);res.status(500).json({message:"Erro interno"})}});
app.get("/api/payment/:tx",async(req,res)=>{try{const STATUS_BASE=process.env.PLUSPIX_STATUS_BASE_URL||"https://api.whitelabel-elite.com";const r=await fetch(STATUS_BASE+"/v1/transactions/"+encodeURIComponent(req.params.tx),{headers:headers()});const d=await r.json().catch(()=>({}));if(r.ok){const status=String(d.status||"").toUpperCase();if(status){db.prepare("UPDATE payments SET status=?,raw_json=? WHERE transaction_id=?").run(status,JSON.stringify(d),req.params.tx);if(["PAGO","PAID","COMPLETO","COMPLETED","APROVADO","APPROVED"].includes(status))db.prepare("UPDATE orders SET status='PAGO' WHERE transaction_id=?").run(req.params.tx)}}res.status(r.ok?200:r.status).json(d)}catch(e){console.error(e);res.status(500).json({message:"Erro ao consultar pagamento"})}});
app.post("/api/webhook/pluspix",(req,res)=>{console.log("WEBHOOK",JSON.stringify(req.body));res.sendStatus(200)});
app.get("/api/admin/orders",admin,(req,res)=>res.json(db.prepare("SELECT * FROM orders ORDER BY id DESC").all()));
app.get("/api/admin/products",admin,(req,res)=>res.json(db.prepare("SELECT id,name,description,image,price,stock,active FROM products ORDER BY id DESC").all()));
app.post("/api/admin/products",admin,(req,res)=>{const {name,description="",image="",price,stock}=req.body;if(!name||price===""||stock==="")return res.status(400).json({message:"Preencha nome, preço e estoque"});const img=saveImage(image);const r=db.prepare("INSERT INTO products(name,diameter,finish,description,image,price,stock,active) VALUES(?,?,?,?,?,?,?,1)").run(name,"","",description,img,Number(price),Number(stock));res.json({id:r.lastInsertRowid})});
app.patch("/api/admin/products/:id",admin,(req,res)=>{const old=db.prepare("SELECT * FROM products WHERE id=?").get(req.params.id);if(!old)return res.status(404).json({message:"Produto não encontrado"});const image=req.body.imageData?saveImage(req.body.imageData):(req.body.image??old.image);db.prepare("UPDATE products SET name=?,description=?,image=?,price=?,stock=?,active=? WHERE id=?").run(req.body.name??old.name,req.body.description??old.description,image,Number(req.body.price??old.price),Number(req.body.stock??old.stock),(req.body.active??old.active)?1:0,req.params.id);res.json({success:true})});
app.get("/api/admin/balance",admin,async(req,res)=>{try{const r=await fetch(BASE+"/api/v1/balance",{headers:headers()});res.status(r.ok?200:r.status).json(await r.json())}catch(e){res.status(500).json({message:"Erro no saldo"})}});
app.post("/api/admin/withdraw",admin,async(req,res)=>{try{const {amount,pixKey,pixKeyType,description}=req.body;const r=await fetch(BASE+"/api/v1/withdraw",{method:"POST",headers:headers(),body:JSON.stringify({amount:Number(amount),pixKey,pixKeyType,description})});res.status(r.ok?200:r.status).json(await r.json())}catch(e){res.status(500).json({message:"Erro no saque"})}});
app.listen(PORT,()=>console.log(`URUGUAY FARM: http://localhost:${PORT}`));